// Generated by: gen
// TypeWriter: slice
// Directive: +gen on *ProxyConf

package yaml

import "errors"

// ProxyConfSlice is a slice of type *ProxyConf. Use it where you would use []*ProxyConf.
type ProxyConfSlice []*ProxyConf

// Where returns a new ProxyConfSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv ProxyConfSlice) Where(fn func(*ProxyConf) bool) (result ProxyConfSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// All verifies that all elements of ProxyConfSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv ProxyConfSlice) All(fn func(*ProxyConf) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Any verifies that one or more elements of ProxyConfSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv ProxyConfSlice) Any(fn func(*ProxyConf) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv ProxyConfSlice) First(fn func(*ProxyConf) bool) (result *ProxyConf, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no ProxyConfSlice elements return true for passed func")
	return
}
