// Generated by: gen
// TypeWriter: slice
// Directive: +gen on *User

package entity

import "errors"

// UserSlice is a slice of type *User. Use it where you would use []*User.
type UserSlice []*User

// Where returns a new UserSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv UserSlice) Where(fn func(*User) bool) (result UserSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// All verifies that all elements of UserSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv UserSlice) All(fn func(*User) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Any verifies that one or more elements of UserSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv UserSlice) Any(fn func(*User) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv UserSlice) First(fn func(*User) bool) (result *User, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no UserSlice elements return true for passed func")
	return
}
